# Site settings
title:          islewis
description:    "Just some thoughts"
url:            islewis.xyz

# Author
author:
  name:         Isaiah Lewis
  #email:       example@gmail.com
  url:          islewis.xyz

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  #email: example@gmail.com
  github: https://github.com/islewis
  linkedin: https://www.linkedin.com/in/isalewis/
